[pytest]
render_collapsed = True
plugins = test_custom_link
md_report_success_color = green
md_report_skip_color = yellow
md_report_error_color = red
md_report_color = text
md_report_verbose = 0

addopts = -p no:warnings -rA -s --show-capture=no --strict-markers

python_files = test*py
markers =
    p0
    p1
    p2
    p3